import Trunk from '../components/front/trunk/Trunk'
import Header from '../components/front/header/Header'
import Head from 'next/head'

const Front = () => {
    return <article className="container">

    <Head>
        <title>Belladonna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

        <Header image="one" tam="11rem" pos="center" num={2}/>
        <Trunk/>

        <style jsx>{`

            .container {
                display: grid;
                grid-template-columns: 1fr;
            }

        `}</style>
    </article>
}

export default Front