import Head from 'next/head'
import Front from './Front'
import styles from '../styles/Home.module.css'

const Index = () => {
    return <main className={styles.main}>
    <Head>
        <title>Belladonna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Front/>


        <style jsx>{`

        `}</style>
    </main>
}

export default Index