import Head from 'next/head'
import { useState } from 'react'
import DescriptionCard from '../components/depilation/DescriptionCard'
import Front from '../components/depilation/Front'
import About from '../components/front-page/About'
import Logo from '../components/header/Logo'
import Nav from '../components/header/Nav'

const Depilacion = () => {
    const [cardSelected, SetcardSelected] = useState(false)

    return <section className="container">
        <Head>
            <title>Depilación femenina</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <Nav/>
        </header>
        <div className="navegation">
            <div className="logo">
                <Logo tam="11em"/>
            </div>
            <div className="menu">
                <Nav pos="" text="inicio" id={5} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="cuerpo completo" id={1} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="superior" id={2} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="bikini" id={3} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="inferior" id={4} setcardSelected={SetcardSelected}/>
            </div>
        </div>
        <div className="wrapper">
            {cardSelected === 5 ? <Front /> : cardSelected ? <DescriptionCard cardSelected={cardSelected}/> : <Front />}
        </div>
        <div className="aboutContainer">
            <About/>
        </div>
        <style jsx>{`
      .container {
        font-family: var(--font);
        height: 191vh;
        width: 100%;
        position: relative;
        background-color: var(--purple-blanco);
        display: grid;
        grid-template-columns: 0.3fr 1fr;
        grid-template-rows: 0.1fr 1fr 1fr auto;
      }
      header{
        grid-column: 2/3;
        grid-row: 1/2;
      }
      .navegation{
        grid-column: 1/2;
        grid-row: 1/3;
        background: var(--prueba);
        display: flex;
        flex-direction: column;
        justify-items: center;
        align-items: center;
        background-color: var(--light-pink);
      }
      .logo{
        height: 100%;
        width: 90%;
        display: grid;
      }
      .menu{
        height: 100%;
        width: 90%;
        display: grid;
      }
      .wrapper{
        grid-column: 2/3;
        grid-row: 2/3;
        box-sizing: border-box;
        display: grid;
        position: relative;
      }
      .aboutContainer{
        grid-column: 1/3;
        grid-row: 3/4;
      }
    `}</style>
    </section>
}

export default Depilacion
