import { useState } from 'react'
import DescriptionCard from '../components/depilation/DescriptionCard'
import Head from 'next/head'
import Menu from '../components/header/Menu'
import Logo from '../components/header/Logo'
import Nav from '../components/depilation/Nav'


const Depilation = () => {

    const [cardSelected, SetcardSelected] = useState([]);

    return <section className="container">

        <Head>
            <title>Depilación femenina</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
            <Menu/>
        </header>

        <div className="navegation">
            <div className="logo">
                <Logo tam="11em"/>
            </div>
            <div className="menu">
                <Nav pos="" text="cuerpo completo" id={1} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="superior" id={2} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="bikini" id={3} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="inferior" id={4} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="promociones" id={5} setcardSelected={SetcardSelected}/>
            </div>
        </div>

        <div className="wrapper">
            <DescriptionCard cardSelected={cardSelected}/>
        </div>
        <style jsx>{`

            .container {
                font-family: 'Karla', sans-serif;
                height: 100vh;
                width: 100%;
                background-color: var(--light-pink);
                display: grid;
                grid-template-columns: 0.3fr 1fr;
                grid-template-rows: 0.1fr 1fr;
            }
            header{
                grid-column: 2/3;
                grid-row: 1/2;
            }
            .navegation{
                grid-column: 1/2;
                grid-row: 1/3;
                background: var(--prueba);
                display: flex;
                flex-direction: column;
                justify-items: center;
                align-items: center;
            }
            .logo{
                height: 100%;
                width: 90%;
                display: grid;
            }
            .menu{
                height: 100%;
                width: 90%;
                display: grid;
            }
            .wrapper{
                grid-column: 2/3;
                grid-row: 2/3;
                display: grid;
                align-items: center;
                justify-items: center;
                position: relative;
                box-sizing: border-box;
            }
        `}</style>
    </section>
}

export default Depilation
