import Head from 'next/head'
import { useState } from 'react'
import DescriptionCard from '../components/depilation/DescriptionCard'
import Front from '../components/depilation/Front'
import NavDepilation from '../components/depilation/NavDepilation'
import About from '../components/front-page/About'
import Logo from '../components/header/Logo'
import Nav from '../components/header/Nav'

const Depilacion = () => {
    const [cardSelected, SetcardSelected] = useState(false)

    return <section className="container">
        <Head>
            <title>Depilación Belladonna</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <Logo/>
            <Nav/>
        </header>
        <div className="menu">
            <NavDepilation text="Información" id={5} setcardSelected={SetcardSelected}/>
            <NavDepilation text="cuerpo completo" id={1} setcardSelected={SetcardSelected}/>
            <NavDepilation text="superior" id={2} setcardSelected={SetcardSelected}/>
            <NavDepilation text="bikini" id={3} setcardSelected={SetcardSelected}/>
            <NavDepilation text="inferior" id={4} setcardSelected={SetcardSelected}/>
        </div>
        <div className="wrapper">
            {cardSelected === 5 ? <Front /> : cardSelected ? <DescriptionCard cardSelected={cardSelected}/> : <Front />}
        </div>
        <div className="aboutContainer">
            <About/>
        </div>
        <style jsx>{`
            .container {
                font-family: var(--font);
                background-color: var(--purple-blanco);
                display: grid;
                grid-template-columns: 0.15fr 1fr;
                grid-template-rows: 0.2fr 1fr;
                height: 100vh;
            }
            header{
                grid-column: 2/3;
                justify-self: center;
                display: flex;
            }
            .menu{
                grid-column: 1/2;
                border-radius: 0 15px 0 0;
                background-color: var(--light-pink);
                height: 100%;
                width: 100%;
                display: grid;
            }
            .wrapper{
                grid-column: 2/3;
                box-sizing: border-box;
                display: grid;
                position: relative;
            }
            .aboutContainer{
                grid-column: 1/3;
            }
        `}</style>
    </section>
}

export default Depilacion
