import { useState } from 'react'
import DescriptionCard from '../components/depilation/DescriptionCard'
import Head from 'next/head'
import Menu from '../components/header/Menu'
import Logo from '../components/header/Logo'
import Nav from '../components/depilation/Nav'


const Depilation = () => {

    const [cardSelected, SetcardSelected] = useState([]);

    return <section className="container">

        <Head>
            <title>Depilación femenina</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
            <Menu/>
        </header>

        <div className="navegation">
            <div className="logo">
                <Logo tam="11em"/>
            </div>
            <div className="menu">
                <Nav pos="" text="cuerpo completo" id={1} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="superior" id={2} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="bikini" id={3} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="inferior" id={4} setcardSelected={SetcardSelected}/>
                <Nav pos="" text="promociones" id={5} setcardSelected={SetcardSelected}/>
            </div>
        </div>

        <div className="wrapper">
            <DescriptionCard cardSelected={cardSelected}/>
        </div>
        <div className="footer">
            <article className="contact">
                    <h1>¿Preguntas?</h1>
                    <div className="nets">
                        <svg viewBox="0 0 512 512"> <path color="#0f91f3" fill="currentcolor" d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg>
                        <svg viewBox="0 0 512 512"> <path color="#0f91f3" fill="currentcolor"d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/></svg>
                        <svg viewBox="0 0 448 512"> <path color="#ff9e11" fill="currentcolor" d="M162.4 196c4.8-4.9 6.2-5.1 36.4-5.1 27.2 0 28.1.1 32.1 2.1 5.8 2.9 8.3 7 8.3 13.6 0 5.9-2.4 10-7.6 13.4-2.8 1.8-4.5 1.9-31.1 2.1-16.4.1-29.5-.2-31.5-.8-10.3-2.9-14.1-17.7-6.6-25.3zm61.4 94.5c-53.9 0-55.8.2-60.2 4.1-3.5 3.1-5.7 9.4-5.1 13.9.7 4.7 4.8 10.1 9.2 12 2.2 1 14.1 1.7 56.3 1.2l47.9-.6 9.2-1.5c9-5.1 10.5-17.4 3.1-24.4-5.3-4.7-5-4.7-60.4-4.7zm223.4 130.1c-3.5 28.4-23 50.4-51.1 57.5-7.2 1.8-9.7 1.9-172.9 1.8-157.8 0-165.9-.1-172-1.8-8.4-2.2-15.6-5.5-22.3-10-5.6-3.8-13.9-11.8-17-16.4-3.8-5.6-8.2-15.3-10-22C.1 423 0 420.3 0 256.3 0 93.2 0 89.7 1.8 82.6 8.1 57.9 27.7 39 53 33.4c7.3-1.6 332.1-1.9 340-.3 21.2 4.3 37.9 17.1 47.6 36.4 7.7 15.3 7-1.5 7.3 180.6.2 115.8 0 164.5-.7 170.5zm-85.4-185.2c-1.1-5-4.2-9.6-7.7-11.5-1.1-.6-8-1.3-15.5-1.7-12.4-.6-13.8-.8-17.8-3.1-6.2-3.6-7.9-7.6-8-18.3 0-20.4-8.5-39.4-25.3-56.5-12-12.2-25.3-20.5-40.6-25.1-3.6-1.1-11.8-1.5-39.2-1.8-42.9-.5-52.5.4-67.1 6.2-27 10.7-46.3 33.4-53.4 62.4-1.3 5.4-1.6 14.2-1.9 64.3-.4 62.8 0 72.1 4 84.5 9.7 30.7 37.1 53.4 64.6 58.4 9.2 1.7 122.2 2.1 133.7.5 20.1-2.7 35.9-10.8 50.7-25.9 10.7-10.9 17.4-22.8 21.8-38.5 3.2-10.9 2.9-88.4 1.7-93.9z"/></svg>
                    </div>
                </article>
                <article className="reserve">
                    <h2>¡No te quedes sin tu cita, reserva aquí!</h2>
                    <svg viewBox="0 0 448 512"> <path color="green" fill="currentcolor" d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/></svg>
                </article>
        </div>
        <style jsx>{`

            .container {
                font-family: 'Karla', sans-serif;
                height: 100vh;
                width: 100%;
                position: relative;
                background-color: var(--light-pink);
                display: grid;
                grid-template-columns: 0.3fr 1fr;
                grid-template-rows: 0.1fr 1fr 0.1fr;
            }
            header{
                grid-column: 2/3;
                grid-row: 1/2;
            }
            .navegation{
                grid-column: 1/2;
                grid-row: 1/4;
                background: var(--prueba);
                display: flex;
                flex-direction: column;
                justify-items: center;
                align-items: center;
            }
            .logo{
                height: 100%;
                width: 90%;
                display: grid;
            }
            .menu{
                height: 100%;
                width: 90%;
                display: grid;
            }
            .wrapper{
                grid-column: 2/3;
                grid-row: 2/3;
                box-sizing: border-box;
                display: grid;
            }
            .footer{
                grid-column: 2/3;
                grid-row: 3/4;
                width: 100%;
                justify-self: center;
                display: grid;
                grid-template-columns: 1fr 1fr;
            }
            article{
                background-color: var(--tone-purple);
            }
            .contact{
                grid-column: 1/2;
                box-sizing: border-box;
                display: grid;
                grid-template-rows: 1fr 1fr;
                justify-items: center;
                border-radius: 10px 0 0 0;
            }
            .contact h1{
                margin: 0;
                position: relative;
                top: 10px;
                font-size: 30px;
                font-weight: 700;
                color: var(--purple-blanco);
                text-align: center;
            }
            .contact h2{
                margin: 0;
                grid-column: 1/2;
                font-size: 25px;
                font-weight: 700;
                color: var(--light-purple);
                text-align: center;
            }
            .nets{
                justify-self: center;
                align-self: center;
                position: relative;
                display: flex;
                flex-direction: row;
                gap: 30px;
            }
            .reserve{
                grid-column: 2/3;
                box-sizing: border-box;
                display: grid;
                justify-items: center;
                border-radius: 0 10px 0 0;
            }
            .reserve h2{
                margin: 0;
                position: relative;
                top: 10px;
                grid-column: 1/2;
                font-size: 25px;
                font-weight: 700;
                color: var(--purple-blanco);
                text-align: center;
            }
            svg{
                margin: 0;
                padding: 0;
                width: 40px;
                cursor: pointer;
            }
        `}</style>
    </section>
}

export default Depilation
