import Head from 'next/head'
import { useState } from 'react'
import DescriptionCard from '../components/depilation/DescriptionCard'
import Front from '../components/depilation/Front'
import NavDepilation from '../components/depilation/NavDepilation'
import Logo from '../components/header/Logo'
import Nav from '../components/header/Nav'

const Depilacion = () => {
    const [cardSelected, SetcardSelected] = useState(false)

    return <section className="container">
        <Head>
            <title>Depilación Belladonna</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <Logo/>
            <Nav/>
        </header>
        <div className="menu">
            <NavDepilation text="Información" id={5} setcardSelected={SetcardSelected}/>
            <NavDepilation text="cuerpo completo" id={1} setcardSelected={SetcardSelected}/>
            <NavDepilation text="superior" id={2} setcardSelected={SetcardSelected}/>
            <NavDepilation text="bikini" id={3} setcardSelected={SetcardSelected}/>
            <NavDepilation text="inferior" id={4} setcardSelected={SetcardSelected}/>
        </div>
        <div className="wrapper">
            {cardSelected === 5 ? <Front /> : cardSelected ? <DescriptionCard cardSelected={cardSelected}/> : <Front />}
        </div>
        <div className="aboutContainer">
            {/* <About/> */}
        </div>
        <style jsx>{`
            .container {
                font-family: var(--font);
                background-color: var(--purple-blanco);
                display: grid;
                grid-template-columns: 0.15fr 1fr;
                max-width: 1590px;
                min-width: 400px;
                margin: auto;
            }
            header{
                grid-column: 2/3;
                justify-self: center;
                display: flex;
            }
            .menu{
                grid-column: 1/2;
                border-radius: 0 15px 0 0;
                background-color: var(--light-pink);
                width: 100%;
                display: grid;
            }
            .wrapper{
                grid-column: 2/3;
                display: grid;
                height: calc( 100vh - 5.3em);
                max-height: 1000px;
                min-height: 400px;
            }
            .aboutContainer{
                grid-column: 1/3;
                outline: 1px solid black;
            }

            @media screen and (max-width: 1200px){
                .menu{
                    font-size: 15px;
                }
            }

            @media screen and (max-width: 1130px){
                .menu{
                    font-size: 14px;
                }
            }

            @media screen and (max-width: 1030px){
                .menu{
                    font-size: 13px;
                }
            }

            @media screen and (max-width: 1000px){
                .menu{
                    font-size: 12px;
                    height: 70%;
                    align-self: center;
                    border-radius: 0 15px 15px 0;
                }
            }

            @media screen and (max-width: 870px){
                .container {
                    grid-template-columns: 1fr;
                    grid-template-rows: auto auto 1fr;
                }

                header{
                    grid-column: 1/3;
                    margin: 0 0 3em 0;
                }

                .menu{
                    grid-column: 1/3;
                    align-self: start;
                    display: flex;
                    gap: 7%;
                    justify-content: center;
                    height: 100%;
                    border-radius: 15px;
                }

                .wrapper{
                    grid-column: 1/3;
                    display: grid;
                }
            }
        `}</style>
    </section>
}

export default Depilacion
