import Head from 'next/head'
import Header from '../components/header/Header'
import FrontLayout from '../components/front-page/FrontLayout'
import HoWork from '../components/front-page/HoWork'
import OurServices from '../components/front-page/OurServices'
import About from '../components/front-page/About'
import WhatsappButton from '../components/WhatsappButton'

const Front = () => {
  return <main className="container">
    <Head>
      <title>Belladonna</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <WhatsappButton href="https://wa.me/message/D4KMZ4C5TFU5N1"/>
    <Header row="1/2" color="--purple-blanco"/>
    <FrontLayout row="1/2"/>
    <div className="hoWorkTitle">
      <h1 className='title1'>¿Cómo trabajamos?</h1>
      <p>Disfruta de la mejor depilación profesional en Bogotá. ¡Reserva tu cita y vive una experiencia única!</p>
    </div>
    <HoWork row="3/4"/>
    <h1 className='title2'>Nuestros servicios</h1>
    <OurServices row="5/6" image="/img/front-page/depilacion.jpeg" sub="Servicio exclusivo para mujeres" title="Depilación con cera" paragraph="Depilación con cera de alta calidad en todas las áreas del cuerpo." href={1} pad="4em"/>
    <OurServices row="6/7"image="/img/front-page/joyas.jpeg" sub="Oro, plata y bisutería" title="Joyería" paragraph="¡No te quedes sin conocer nuestra tienda de joyas!." href={2} pad="9em"/>
    <About/>
    <style jsx>{`
      .container {
        position: relative;
        display: grid;
        width: 100%;
        height: 100%;
        max-width: 2410px;
        grid-template-rows: auto auto auto 86vh 86vh 86vh 100vh;
        box-sizing: border-box;
        font-family: var(--font);
      }
      .hoWorkTitle{
        grid-row: 2/3;
        grid-column: 1/2;
        justify-self: center;
        align-self: center;
        position: relative;
        height: 86vh;
        width: 100%;
        display: grid;
        grid-template-rows: 1fr;
        grid-template-columns: 1fr;
        justify-items: center;
        align-items: center;
        min-height: 19rem;
        max-height: 75rem;
      }
      .title1{
        grid-column: 1/2;
        grid-row: 1/2;
        margin: 0;
        text-align: center;
        font-size: 10rem;
        font-weight: 700;
        color: var(--tone-purple);
        position: relative;
        bottom: 15%;
      }
      p{
        grid-column: 1/2;
        grid-row: 1/2;
        align-self: center;
        position: absolute;
        bottom: 20%;
        text-align: center;
        font-size: 3.5em;
        color: var(--normal-purple);
        box-sizing: border-box;
      }
      .title2{
        grid-row: 4/5;
        grid-column: 1/2;
        justify-self: center;
        align-self: center;
        position: relative;
        bottom: 10%;
        margin: 0;
        text-align: center;
        font-size: 3.75em;
        font-weight: 700;
        color: var(--tone-purple);
      }

      @media screen and (max-width: 2560px) and (max-height: 2560px){
        .title1{
          font-size: 11rem;
        }
        p{
          font-size: 5em;
          box-sizing: border-box;
          margin: 0;
          top: 60%;
          padding: 0 2%;
        }
      }
      @media screen and (max-width: 2560px) and (max-height: 900px){
        .title1{
          font-size: 10.5rem;
        }
        p{
          font-size: 3.5em;
        }
      }
      @media screen and (max-width: 2560px) and (max-height: 580px){
        .title1{
          font-size: 10rem;
        }
        p{
          top: 70%;
          font-size: 2.7em;
        }
      }

      @media screen and (max-width: 1970px) and (max-height: 2560px){
        .title1{
          font-size: 9rem;
        }
        p{
          top: 55%;
          font-size: 3.5em;
        }
      }

      @media screen and (max-width: 1395px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 60rem;
        }
        .title1{
          font-size: 7rem;
        }
        p{
          top: 48%;
          font-size: 3.3em;
        }
      }
      @media screen and (max-width: 1395px) and (max-height: 760px){
        .title1{
          font-size: 7rem;
        }
        p{
          top: 52%;
          font-size: 3em;
        }
      }

      @media screen and (max-width: 1200px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 55rem;
        }
        .title1{
          font-size: 6.3rem;
        }
        p{
          top: 52%;
          font-size: 3em;
          padding: 0 5%;
        }
      }
      @media screen and (max-width: 1200px) and (max-height: 800px){
        .title1{
          font-size: 6rem;
        }
        p{
          top: 54%;
          font-size: 2.8em;
          padding: 0 5%;
        }
      }

      @media screen and (max-width: 975px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 50rem;
        }
        .title1{
          font-size: 5rem;
        }
        p{
          top: 49%;
          font-size: 2.7em;
          padding: 0 5%;
        }
      }
      @media screen and (max-width: 975px) and (max-height: 700px){
        .hoWorkTitle{
          max-height: 50rem;
        }
        .title1{
          font-size: 5rem;
        }
        p{
          top: 55%;
          font-size: 2.1em;
          padding: 0 5%;
        }
      }
      @media screen and (max-width: 775px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 30rem;
        }
        .title1{
          font-size: 4rem;
        }
        p{
          top: 50%;
          font-size: 1.8em;
        }
      }

      @media screen and (max-width: 670px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 25rem;
        }
        .title1{
          font-size: 3rem;
        }
        p{
          top: 50%;
          font-size: 1.55em;
        }
      }

      @media screen and (max-width: 500px) and (max-height: 2560px){
        .hoWorkTitle{
          max-height: 20rem;
        }
        .title1{
          font-size: 2rem;
        }
        p{
          top: 50%;
          font-size: 1.3em;
        }
      }

    `}</style>
    </main>
}

export default Front
