import Head from 'next/head'
import Header from '../components/header/Header'
import FrontLayout from '../components/front-page/FrontLayout'
import HoWork from '../components/front-page/HoWork'
import OurServices from '../components/front-page/OurServices'
import About from '../components/front-page/About'

const Front = () => {

    /* --purple-blanco */
    return <main className="container">
    <Head>
        <title>Belladonna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header row="1/2" color="--purple-blanco"/>
    <FrontLayout row="1/2"/>
    <div className="head"></div>
    <HoWork row="3/4"/>
    <div className="space">
        <div className="head1"></div>
        <h1>Nuestros servicios</h1>
    </div>
    <OurServices row="5/6" image="/img/front-page/depilacion.jpeg" sub="Servicio exclusivo para mujeres" title="Depilación con cera" paragraph="Depilación con cera de alta calidad en todas las áreas del cuerpo." href={1} pad="4em"/>
    <OurServices row="6/7"image="/img/front-page/joyas.jpeg" sub="Joyería" title="Bisutería" paragraph="¡No te quedes sin conocer nuestra tienda de joyas!." href={2} pad="9em"/>
    <About/>

        <style jsx>{`
        .container {
            position: relative;
            display: grid;
            grid-template-columns: 1fr;
            grid-template-rows: 100vh auto 100vh 50vh 100vh 100vh 100vh;
            box-sizing: border-box;
            font-family: var(--font);
        }
        .space{
            grid-row: 4/5;
            height: 100%;
            width: 100%;
            display: flex;
            flex-direction: column;
        }
        .head{
            grid-row: 2/3;
            width: 100%;
            height: 9em;
        }
        .head1{
            width: 100%;
            height: 9em;
        }
        h1{
            text-align: center;
            font-size: 60px;
            font-weight: 700;
            color: var(--tone-purple);
        }
        `}</style>
    </main>
}

export default Front
